# Generated by Django 2.0.2 on 2018-02-25 03:29

import advapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=7)),
                ('category', models.CharField(max_length=30)),
                ('c_type', models.CharField(max_length=30)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('forwarding', models.BooleanField()),
                ('description', models.TextField()),
                ('active_ad', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(upload_to=advapp.models.Advert.user_directory_path)),
                ('image2', models.ImageField(blank=True, upload_to=advapp.models.Advert.user_directory_path)),
                ('image3', models.ImageField(blank=True, upload_to=advapp.models.Advert.user_directory_path)),
                ('image4', models.ImageField(blank=True, upload_to=advapp.models.Advert.user_directory_path)),
                ('favourited_by', models.ManyToManyField(null=True, related_name='favourited_by', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(null=True, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
