# Generated by Django 2.0.2 on 2018-02-25 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advert',
            name='favourited_by',
            field=models.ManyToManyField(related_name='favourited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advert',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
