# Generated by Django 2.0.2 on 2018-02-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0002_auto_20180223_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
