# Generated by Django 2.0.2 on 2018-02-27 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0002_auto_20180225_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='favourited_by',
            field=models.ManyToManyField(null=True, related_name='favourited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advert',
            name='forwarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advert',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
