# Generated by Django 2.0.2 on 2018-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0003_advert_number_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='active_ad',
            field=models.BooleanField(default=True),
        ),
    ]
