# Generated by Django 2.0.2 on 2018-02-23 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0002_auto_20180223_0051'),
        ('userapp', '0002_auto_20180223_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='advapp.Advert'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_likes_recieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_sold_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='advapp.Advert'),
        ),
    ]
