# Generated by Django 2.0.2 on 2018-02-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20180225_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following_people',
            field=models.ManyToManyField(blank=True, related_name='folloing_people', to='userapp.Profile'),
        ),
    ]
