# Generated by Django 2.0.2 on 2018-02-23 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0002_auto_20180223_0051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0003_auto_20180223_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_posts', to='advapp.Advert'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folloing_people', to=settings.AUTH_USER_MODEL),
        ),
    ]
