# Generated by Django 2.0.2 on 2018-02-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20180227_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following_people',
            field=models.ManyToManyField(related_name='folloing_people', to='userapp.Profile'),
        ),
    ]
