# Generated by Django 2.0.2 on 2018-02-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
