# Generated by Django 2.0.2 on 2018-02-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20180223_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fb',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
